apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
type: Opaque
stringData:
  connectionstring: {{ .Values.connectionString }}
  azurestorageaccountname: {{ .Values.storageAccountName }}
  azurestorageaccountkey: {{ .Values.storageAccountKey }}
